import 'dart:convert' as convert;

void main() {
  List<String> cryptoList = [
    "Bitcoin,BTC ",
    "Wrapped Bitcoin,WBTC ",
    "Bitcoin BEP2,BTCB ",
    "yearn.finance,YFI ",
    "Ethereum,ETH ",
    "Maker,MKR ",
    "Binance Coin,BNB ",
    "Bitcoin Cash,BCH ",
    "Kusama,KSM ",
    "Monero,XMR ",
    "Aave,AAVE ",
    "Elrond,EGLD ",
    "Quant,QNT ",
    "Compound,COMP ",
    "Litecoin,LTC ",
    "Zcash,ZEC ",
    "Solana,SOL ",
    "Dash,DASH ",
    "Bitcoin SV,BSV ",
    "Avalanche,AVAX ",
    "Decred,DCR ",
    "Axie Infinity,AXS ",
    "Terra,LUNA ",
    "FTX Token,FTT ",
    "Arweave,AR ",
    "Ethereum Classic,ETC ",
    "Cosmos,ATOM ",
    "Helium,HNT ",
    "Convex Finance,CVX ",
    "Filecoin,FIL ",
    "Internet Computer,ICP ",
    "OKB,OKB ",
    "Neo,NEO ",
    "Polkadot,DOT ",
    "KuCoin Token,KCS ",
    "Chainlink,LINK ",
    "NEAR Protocol,NEAR ",
    "Uniswap,UNI ",
    "Waves,WAVES ",
    "Huobi Token,HT ",
    "Kadena,KDA ",
    "PancakeSwap,CAKE ",
    "Flow,FLOW ",
    "Secret,SCRT ",
    "OMG Network,OMG ",
    "UNUS SED LEO,LEO ",
    "THORChain,RUNE ",
    "The Sandbox,SAND ",
    "Tezos,XTZ ",
    "Curve DAO Token,CRV ",
    "Render Token,RNDR ",
    "Celo,CELO ",
    "Theta Network,THETA ",
    "Decentraland,MANA ",
    "Celsius,CEL ",
    "Mina,MINA ",
    "EOS,EOS ",
    "Fantom,FTM ",
    "Nexo,NEXO ",
    "Enjin Coin,ENJ ",
    "Polygon,MATIC ",
    "1inch Network,1INCH ",
    "Stacks,STX ",
    "Klaytn,KLAY ",
    "Cardano,ADA ",
    "BORA,BORA ",
    "Loopring,LRC ",
    "Algorand,ALGO ",
    "Tether,USDT ",
    "TrueUSD,TUSD ",
    "TerraUSD,UST ",
    "Binance USD,BUSD ",
    "USD Coin,USDC ",
    "Pax Dollar,USDP ",
    "Dai,DAI ",
    "IOTA,MIOTA ",
    "Basic Attention Token,BAT ",
    "Ripple,XRP ",
    "Crypto.com Coin,CRO ",
    "The Graph,GRT ",
    "Oasis Network,ROSE ",
    "Gala,GALA ",
    "Hedera,HBAR ",
    "Stellar,XLM ",
    "Chiliz,CHZ ",
    "Harmony,ONE ",
    "Theta Fuel,TFUEL ",
    "Symbol,XYM ",
    "Dogecoin,DOGE ",
    "NEM,XEM ",
    "IoTeX,IOTX ",
    "Ravencoin,RVN ",
    "TRON,TRX ",
    "VeChain,VET ",
    "XDC Network,XDC ",
    "Amp,AMP ",
    "Holo,HOT ",
    "eCash,XEC ",
    "BitTorrent New,BTT ",
    "Shiba Inu,SHIB ",
  ];

  Map<String, String> mm = {};
  // ignore: avoid_function_literals_in_foreach_calls
  cryptoList.forEach((val) {
    String symbol = val.split(',')[1].trim();
    String name = val.split(',')[0].trim();
    mm[name] = symbol;
  });

  // ignore: avoid_print
  print(convert.jsonEncode(mm));
}
